/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{db}/hygiene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["hygiene"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{db}/new-slow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["newSlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{db}/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{db}/queries/{queryid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{db}/queries/{queryid}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["explanation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{db}/queries/{queryid}/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{db}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{db}/top-movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["topMovers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/databases/{name}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["acrossDatabases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{username}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["resetPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcrossDatabases: {
            confirm: components["schemas"]["Confirm"];
            recommended: components["schemas"]["IndexRecommendation"][];
        };
        AgentCredentials: {
            agentToken: string;
            database: components["schemas"]["Database"];
        };
        ApiToken: {
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            lastUsedAt: string | null;
            name: string;
        };
        Confirm: {
            caveat: string;
            command: string;
        };
        CreatedToken: {
            info: components["schemas"]["ApiToken"];
            token: string;
        };
        Database: {
            /** @enum {string} */
            agent: "NEVER_CONNECTED" | "CONNECTED" | "STALE";
            /** Format: date-time */
            createdAt: string;
            host: string | null;
            /** Format: date-time */
            lastIngestAt: string | null;
            name: string;
        };
        ExplanationView: {
            ddl: string;
            docs: string[];
            /** Format: date-time */
            generatedAt: string | null;
            model: string | null;
            promptVersion: string | null;
            source: string;
            summary: string;
            whatTheIndexChanges: string;
            whyItIsSlow: string;
        };
        Explanations: {
            database: string;
            explanations: components["schemas"]["ExplanationView"][];
            queryid: string;
        };
        FindingView: {
            columns: string[];
            confidence: string;
            evidence: string;
            /** Format: int32 */
            planNode: number | null;
            ruleId: string;
            table: string | null;
            title: string;
        };
        Health: {
            status: string;
            version: string;
        };
        Hygiene: {
            database: string;
            findings: components["schemas"]["IndexHygieneFinding"][];
        };
        IndexHygieneFinding: {
            definition: string;
            indexName: string;
            /** @enum {string} */
            kind: "DUPLICATE" | "REDUNDANT" | "UNUSED";
            reason: string;
            relatedIndex: string | null;
            table: string;
        };
        IndexRecommendation: {
            accessMethod: string;
            actionable: boolean;
            buildCaution: string | null;
            database: string;
            ddl: string;
            /** Format: double */
            estimatedMsSaved: number;
            footprintLabel: string | null;
            queries: components["schemas"]["QueryEvidence"][];
            redundantWith: string | null;
            table: string | null;
            writeLoad: components["schemas"]["TableWriteLoad"] | null;
        };
        Leaderboard: {
            /** Format: date-time */
            from: string;
            items: components["schemas"]["LeaderboardEntry"][];
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            sort: string;
            /** Format: date-time */
            to: string;
            /** Format: int64 */
            total: number;
            window: string;
        };
        LeaderboardEntry: {
            /** Format: int64 */
            calls: number;
            /** Format: double */
            measuredMeanMs: number | null;
            /** Format: double */
            measuredTotalMs: number;
            planCaptured: boolean;
            queryid: string;
            recommendation: string | null;
            /** Format: int64 */
            rows: number;
            /** Format: int64 */
            sharedBlksHit: number;
            /** Format: int64 */
            sharedBlksRead: number;
            sqlPreview: string;
            sqlPreviewCut: boolean;
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        LoginResponse: {
            /** Format: date-time */
            expiresAt: string;
            token: string;
            user: components["schemas"]["UserView"];
        };
        Me: {
            authRequired: boolean;
            /** @enum {string} */
            role: "ADMIN" | "VIEWER";
            username: string;
            /** @enum {string} */
            via: "SESSION" | "API_TOKEN" | "AUTH_DISABLED";
        };
        MeasuredTotals: {
            /** Format: date-time */
            asOf: string;
            /** Format: int64 */
            calls: number;
            /** Format: double */
            measuredMeanMs: number | null;
            /** Format: double */
            measuredTotalMs: number;
            /** Format: int64 */
            rows: number;
        };
        NewDatabase: {
            name: string;
        };
        NewPassword: {
            password: string;
        };
        NewSlow: {
            database: string;
            /** Format: date-time */
            from: string;
            items: components["schemas"]["NewSlowView"][];
            /** Format: double */
            minTotalMs: number;
            /** Format: date-time */
            to: string;
            window: string;
        };
        NewSlowView: {
            /** Format: int64 */
            calls: number;
            /** Format: date-time */
            firstSeen: string;
            /** Format: double */
            measuredMeanMs: number | null;
            /** Format: double */
            measuredTotalMs: number;
            queryid: string;
            sql: string;
        };
        NewToken: {
            name: string;
        };
        NewUser: {
            password: string;
            /** @enum {string} */
            role: "ADMIN" | "VIEWER";
            username: string;
        };
        NotPlannerValidated: {
            accessMethod: string;
            ddl: string;
            queryids: string[];
            reason: string | null;
        };
        PasswordChange: {
            currentPassword: string;
            newPassword: string;
        };
        PlanNodeView: {
            alias: string | null;
            children: components["schemas"]["PlanNodeView"][];
            /** Format: int64 */
            estimatedRows: number;
            /** Format: double */
            estimatedStartupCost: number;
            /** Format: double */
            estimatedTotalCost: number;
            /** Format: int32 */
            estimatedWidth: number;
            filter: string | null;
            hashCond: string | null;
            /** Format: int32 */
            id: number;
            index: string | null;
            indexCond: string | null;
            joinType: string | null;
            nodeType: string;
            parallelAware: boolean;
            recheckCond: string | null;
            relation: string | null;
            sortKeys: string[];
            /** Format: int32 */
            workersPlanned: number | null;
        };
        PlanView: {
            captureMode: string;
            /** Format: double */
            estimatedTotalCost: number;
            label: string;
            root: components["schemas"]["PlanNodeView"];
        };
        QueryDetail: {
            confirm: components["schemas"]["Confirm"];
            database: string;
            findings: components["schemas"]["FindingView"][];
            /** Format: date-time */
            firstSeen: string;
            inWindow: components["schemas"]["MeasuredTotals"];
            /** Format: date-time */
            lastSeen: string;
            plan: components["schemas"]["PlanView"] | null;
            planUnavailableReason: string | null;
            queryid: string;
            recommendations: components["schemas"]["QueryRecommendation"][];
            sinceStatsReset: components["schemas"]["MeasuredTotals"] | null;
            sql: string;
            sqlTruncated: boolean;
            window: string;
        };
        QueryEvidence: {
            /** Format: double */
            estimatedMsSaved: number;
            /** Format: double */
            plannerCostDropFraction: number;
            queryid: string;
            rangeLabel: string | null;
            scoreBasis: string | null;
            sqlPreview: string | null;
        };
        QueryRecommendation: {
            accessMethod: string;
            buildCaution: string | null;
            ddl: string;
            /** Format: double */
            estimatedMsSaved: number | null;
            footprintLabel: string | null;
            /** Format: double */
            plannerCostAfter: number | null;
            /** Format: double */
            plannerCostBefore: number | null;
            /** Format: double */
            plannerCostDropFraction: number | null;
            rangeLabel: string | null;
            reason: string | null;
            scoreBasis: string | null;
            status: string;
            usedByPlanner: boolean | null;
            /** Format: date-time */
            validatedAt: string;
        };
        Recommendations: {
            confirm: components["schemas"]["Confirm"];
            database: string;
            notPlannerValidated: components["schemas"]["NotPlannerValidated"][];
            recommended: components["schemas"]["IndexRecommendation"][];
        };
        TableActivity: {
            /** Format: int64 */
            deleted: number;
            /** Format: int64 */
            inserted: number;
            /** Format: int64 */
            tuplesRead: number;
            /** Format: int64 */
            updated: number;
        };
        TableWriteLoad: {
            activity: components["schemas"]["TableActivity"] | null;
            label: string;
            /** @enum {string} */
            level: "WRITE_DOMINANT" | "READ_DOMINANT" | "NO_ACTIVITY";
            table: string;
            window: string;
        };
        TopMoverView: {
            /** Format: double */
            deltaMs: number;
            /** Format: double */
            measuredPriorTotalMs: number;
            /** Format: double */
            measuredRecentTotalMs: number;
            /** Format: double */
            pctChange: number | null;
            queryid: string;
            sql: string;
        };
        TopMovers: {
            database: string;
            /** Format: date-time */
            from: string;
            items: components["schemas"]["TopMoverView"][];
            /** Format: date-time */
            to: string;
            window: string;
        };
        Trend: {
            /** Format: date-time */
            from: string;
            points: components["schemas"]["TrendPointView"][];
            queryid: string;
            resolution: string;
            /** Format: date-time */
            to: string;
        };
        TrendPointView: {
            /** Format: int64 */
            calls: number;
            /** Format: date-time */
            capturedAt: string;
            /** Format: double */
            measuredMeanMs: number | null;
            /** Format: double */
            measuredTotalMs: number;
        };
        UserView: {
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            role: "ADMIN" | "VIEWER";
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiToken"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewToken"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedToken"];
                };
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Database"][];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewDatabase"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCredentials"];
                };
            };
        };
    };
    hygiene: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                db: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hygiene"];
                };
            };
        };
    };
    newSlow: {
        parameters: {
            query?: {
                window?: string;
                minTotalMs?: number;
                limit?: number;
            };
            header?: never;
            path: {
                db: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewSlow"];
                };
            };
        };
    };
    leaderboard: {
        parameters: {
            query?: {
                window?: string;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                db: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: {
                window?: string;
            };
            header?: never;
            path: {
                db: string;
                queryid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryDetail"];
                };
            };
        };
    };
    explanation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                db: string;
                queryid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanations"];
                };
            };
        };
    };
    trend: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                resolution?: string;
            };
            header?: never;
            path: {
                db: string;
                queryid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trend"];
                };
            };
        };
    };
    recommendations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                db: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendations"];
                };
            };
        };
    };
    topMovers: {
        parameters: {
            query?: {
                window?: string;
                limit?: number;
            };
            header?: never;
            path: {
                db: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMovers"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Database"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: {
                confirm?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotateToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCredentials"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acrossDatabases: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcrossDatabases"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewUser"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPassword"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
